##       ======= Poor Man's Spice =======
## Copyright (C) 2018 Carlos Novo, Francisco Pimenta
##
## Based on Werner Hoch's spice_readfile. As such, distributed under the same
## license: GNU General Purpose License.
##
## Before running, install ngspice.
##
## Authors: Carlos Novo and Francisco Pimenta
## Description: Functions to easily import, display and process rawdata 
## generated by ngspice.

function [axis, output] = spice_process(filename)
  system(["ngspice -b " filename]);
  k = spice_readfile("rawspice.raw");
  axis = real(k(:,1));
  output = k(:,size(k,2));
endfunction