##       ======= Poor Man's Spice =======
## Copyright (C) 2018 Carlos Novo, Francisco Pimenta
##
## Based on Werner Hoch's spice_readfile. As such, distributed under the same
## license: GNU General Purpose License.
##
## Before running, install ngspice.
##
## Authors: Carlos Novo and Francisco Pimenta
## Description: Functions to easily import, display and process rawdata 
## generated by ngspice.

function [figureAC] = spice_plot_ac(frequencies, value, minfreq, maxfreq, label)
  # Label must be of type ['1K';'10K';'100K';...] (for example)
  if (nargin < 2)
    usage("spice_plot_ac(frequencies, value)");
  endif
  
  figureAC = figure('name', 'AC Analysis');
  semilogx(frequencies, mag2db(abs(value)));
  hold on
  xlabel('Frequency in Hz');
  ylabel('Gain in dB');
  xlim([minfreq maxfreq]);
  disp("Use ylim([mindB maxdB]) to change limits");
  
  if (nargin > 4)
    set(gca, 'XTickLabel', cellstr(label));
  endif
endfunction